### PR TITLE
add form validation using Formik and Yup libraries

### LINKED ISSUE #241: Application form does not have any field validation
### Description

Application form fields are not being validated on the front-end.
- Name should be required
- Email should be required and should be of "email" type (right now form submits successfully even with just "test" as the email)

### Context

- **Browser**:  any
- **OS**: any

### Steps to Reproduce

1. Visit https://commit-staging.dev/apply

- Submit form without filling anything
- Submit with "test" for every field

**Expected behavior:** 
User can see validation errors

**Actual behavior:** 
Form is submitted to the server

### PR DESCRIPTION
**Pull request by ALukonin**
## Reminder

> Please ensure the following criteria is met for this PR. It will help others review your PR and provide confidence things work as expected.

- [x] CI is green
- [x] Link to any related issues
- [x] Received at least 1 approval from core members
- [x] Made sure that changes are obvious for the reviewer (ex meaningful title and commit messages, comments in code or PR where appropriate, screenshots, etc.)

# What Changed?
Add form validation for the three required fields (name, email and resources)

> Related Issue: None / [https://github.com/commitdev/commit.dev/issues/241](241)

- TODO

## Screenshots
Desktop:
desktop form validation
Mobile:
mobile form validation

### CODE REVIEW

**Comment by robyn3choi** [comment]
Couple of suggestions:
- I think we should either not have the "what commit resources" field be required, or have an option that says "other"
- maybe we could disable the "apply" button if the user hasn't entered all the required fields.
- this isn't part of your changes but might as well correct the typo "Woops, the application failed to send" -> "Whoops, [...]"

**Comment by anikey** [comment]
1. "What commit resources" was a asking from the growth/epx team so we shall keep it but agree we can add in the option for 'other' and best to then give users the ability to type in what resource that is
2. One issue with disabling the apply button is sometimes people don't see what they missed until you point it out to them, it most likely won't happen with our form as it's short but let's have the apply button be there and point out any errors after.
3. Yes please go ahead and correct the "woops" : )

**Comment by robyn3choi** [comment]
Sorry by "disable" the apply button, I meant that it's still visible, it's just unable to be clicked (so it would appear darker or greyed out). That way the user knows there's something missing in the form.

It feels weird to show them errors indicating that they didnt add an email address, and then let them click the apply button anyway.

**Comment by ALukonin** [comment]
I also added a character limit of 250 to the info textarea section, since this is going into a google sheet I figured it should be limited for any malicious attempts and general readability from the google sheet.

Disabling the apply button may be misleading, especially on mobile, since the dropdown is required and may be missed. It could be clarified using an asterisk for the required fields?

**Comment by robyn3choi** [comment]
Isn't disabling the apply button less misleading if the user is missing a required field? If the user missing a field and clicks the apply button, and then the application fails, they wouldn't know why it failed.

**Comment by anikey** [comment]
One thing with disabling the button ( this applys more to longer forms ) is that some users do not realize that they are missing fields until we point them out, so they go ahead click on apply in which we then point to them the missing field they need to input or any other errors.

When we disable the button users may find it frustrating that they can't click, especially if they don't realize they are missing fields,as it doesn't give users any feedback

**Comment by robyn3choi** [comment]
Ohh, so when the user has missing fields and they click the apply button, does it show error text or scroll them up to the missing field? If that's the case, then I think that works too. I assumed that clicking the button would send the request and then the "Whoops" text would appear which isn't enough info.

**Comment by ALukonin** [comment]
> Isn't disabling the apply button less misleading if the user is missing a required field? If the user missing a field and clicks the apply button, and then the application fails, they wouldn't know why it failed.

Sorry let me clarify what I meant. With this PR, if the user misses a required input, the form doesn't submit and an error message shows above the missing, required field. After the validation is passed, the form submits to the server.

If we disable the button, the form validation wont trigger unless they focus or change a required form field. We could add an asterisk to show what is required as they browse the form while the Apply button is still disabled.

**Comment by ALukonin** [comment]
> Ohh, so when the user has missing fields and they click the apply button, does it show error text or scroll them up to the missing field? If that's the case, then I think that works too. I assumed that clicking the button would send the request and then the "Whoops" text would appear which isn't enough info.

The "Whoops" text appears after form submission and the server returns an error (currently, anything other than a 200)

**Comment by robyn3choi** [comment]
I see, I thought the form validation only happened when the user focuses/changes a required field. Thanks for clarifying!

**Review by robyn3choi — APPROVED** [review]

**Pull request merged**
