### PR TITLE
Fix header to show light variant on pages that are not the home page

### PR DESCRIPTION
**Pull request by alebiavati**
## Reminder

> Please ensure the following criteria is met for this PR. It will help others review your PR and provide confidence things work as expected.

- [ ] CI is green
- [ ] Link to any related issues
- [ ] Received at least 1 approval from core members
- [ ] Made sure that changes are obvious for the reviewer (ex meaningful title and commit messages, comments in code or PR where appropriate, screenshots, etc.)

# What Changed?

Fix header to show light variant on pages that are not the home page.
Before this change the header doesn't show on the about page.

## Screenshots

Screen Shot 2021-04-07 at 12 29 02 PM

Screen Shot 2021-04-07 at 12 28 59 PM

### CODE REVIEW

**Review by chrisnottca — APPROVED** [review]

**Comment by ALukonin** [comment]
Hey Ale, it looks good! I just noticed one thing - the apply page, seems the color theme is backwards on that page

**Comment by alebiavati** [comment]
@ALukonin ah! good point. I'll fix up that page.

**Comment by alebiavati** [comment]
@ALukonin Fixed!

**Comment by ALukonin** [comment]
@alebiavati Looks good!

**Pull request merged**
