### PR TITLE
#35 adjust column breakpoint to 1023px

### PR DESCRIPTION
**Pull request by adriandelisle**
## Reminder

> Please ensure the following criteria is met for this PR. It will help others review your PR and provide confidence things work as expected.

- [x] CI is green
- [x] Link to any related issues
- [ ] Received at least 1 approval from core members
- [x] Made sure that changes are obvious for the reviewer (ex meaningful title and commit messages, comments in code or PR where appropriate, screenshots, etc.)

# What Changed?

- Changed the column break point from `767px` to `1023px`

> Related Issue: #35 

## Screenshots
Kapture 2021-02-09 at 15 53 35-min

### CODE REVIEW

**Review by superkhau — APPROVED** [review]

**Review by superkhau — CHANGES_REQUESTED** [review]
Why are there two 1023px min widths?

**Comment by jasondippel** [comment]
> Why are there two 1023px min widths?

@superkhau I see one min and one max. Where do you see the two min widths?

**Review by superkhau — APPROVED** [review]

**Comment by superkhau** [comment]
@jasondippel I don't see it anymore LOL, was probably tired. ;p LGTM

**Comment by superkhau** [comment]
Thanks @adriandelisle for the contribution. 🚀

**Pull request merged**
